# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0016_auto_20190327_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transisi',
            name='status_perpindahan',
            field=models.CharField(choices=[('CONVEYOR', 'CONVEYOR'), ('GUDANG TRANSISI', 'GUDANG TRANSISI'), ('GUDANG RACKING', 'GUDANG RACKING')], max_length=100),
        ),
    ]
