# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0017_auto_20190327_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transisi',
            name='product_per_palet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi.productperpalet'),
        ),
    ]
