# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jenis',
            fields=[
                ('jenis_id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='komputer',
            fields=[
                ('komputer_id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_komputer', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('pengguna', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=100)),
                ('kondisi', models.CharField(choices=[('OK', 'OK'), ('RUSAK', 'RUSAK')], default='OK', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='memory',
            fields=[
                ('memory_id', models.AutoField(primary_key=True, serialize=False)),
                ('merek_memory', models.CharField(max_length=100)),
                ('ddr', models.CharField(choices=[('DDR1', 'DDR1'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4')], default='DDR2', max_length=100)),
                ('kapasitas', models.CharField(choices=[('1Gb', '1Gb'), ('2Gb', '2Gb'), ('4Gb', '4Gb'), ('8Gb', '8Gb')], default='1 Gb', max_length=100)),
                ('kondisi', models.CharField(choices=[('OK', 'OK'), ('RUSAK', 'RUSAK')], default='OK', max_length=100)),
                ('dipakai_pada_komputer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.komputer')),
            ],
        ),
        migrations.CreateModel(
            name='psu',
            fields=[
                ('psu_id', models.AutoField(primary_key=True, serialize=False)),
                ('merek_psu', models.CharField(max_length=100)),
                ('kapasitas_psu', models.CharField(choices=[('350 Watt', '350 Watt'), ('400 Watt', '400 Watt'), ('450 Watt', '450 Watt'), ('500 Watt', '500 Watt'), ('550 Watt', '550 Watt')], default='400 Watt', max_length=100)),
                ('kondisi', models.CharField(choices=[('OK', 'OK'), ('RUSAK', 'RUSAK')], default='OK', max_length=100)),
                ('dipakai_pada_komputer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.komputer')),
            ],
        ),
        migrations.CreateModel(
            name='sistem_operasi',
            fields=[
                ('sistem_operasi_id', models.AutoField(primary_key=True, serialize=False)),
                ('sistem_operasi', models.CharField(choices=[('Win XP', 'Win XP'), ('Win 7 32bit', 'Win 7 32bit'), ('Win 7 64bit', 'Win 7 64bit'), ('Win 8 32bit', 'Win 8 32bit'), ('Win 8 64bit', 'Win 8 64bit'), ('Win 10 32bit', 'Win 10 32bit'), ('Win 10 64bit', 'Win 10 64bit')], default='Win 7 32bit', max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('dipakai_pada_komputer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.komputer')),
            ],
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('merek_storage', models.CharField(max_length=100)),
                ('kapasitas', models.CharField(choices=[('40Gb', '40Gb'), ('80Gb', '80Gb'), ('120Gb', '120Gb'), ('250Gb', '250Gb'), ('32Gb', '320Gb'), ('500Gb', '500Gb'), ('1Tb', '1Tb'), ('2Tb', '2Tb')], default='1 Gb', max_length=100)),
                ('tipe_storage', models.CharField(choices=[('HDD', 'HDD'), ('SDD', 'SDD'), ('M2', 'M2')], default='HDD', max_length=100)),
                ('kondisi', models.CharField(choices=[('OK', 'OK'), ('RUSAK', 'RUSAK')], default='OK', max_length=100)),
                ('dipakai_pada_komputer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.komputer')),
            ],
        ),
    ]
