# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190215_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='komputer',
            name='serial_number',
            field=models.CharField(default='please update', max_length=100),
            preserve_default=False,
        ),
    ]
