# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_komputer_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='dvr',
            fields=[
                ('dvr_id', models.AutoField(primary_key=True, serialize=False)),
                ('merek_dvr', models.CharField(max_length=100)),
                ('tipe_cctv', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('lokasi_dvr', models.CharField(max_length=100)),
                ('kondisi', models.CharField(choices=[('OK', 'OK'), ('RUSAK', 'RUSAK')], default='OK', max_length=100)),
                ('catatan', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pabx',
            fields=[
                ('pabx_id', models.AutoField(primary_key=True, serialize=False)),
                ('merek_pabx', models.CharField(max_length=100)),
                ('tipe_pabx', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('lokasi_pabx', models.CharField(max_length=100)),
                ('kondisi', models.CharField(choices=[('OK', 'OK'), ('RUSAK', 'RUSAK')], default='OK', max_length=100)),
                ('catatan', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
