# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_dvr_pabx'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='interface',
            field=models.CharField(choices=[('PS2', 'PS2'), ('USB', 'USB'), ('WIRELESS', 'WIRELESS'), ('SERIAL', 'SERIAL')], default='USB', max_length=100),
        ),
        migrations.AddField(
            model_name='mouse',
            name='jenis_mouse',
            field=models.CharField(choices=[('OPTIK', 'OPTIK'), ('BOLA', 'BOLA')], default='OPTIK', max_length=100),
        ),
        migrations.AddField(
            model_name='printer',
            name='tipe_tinta',
            field=models.CharField(choices=[('Deskjet', 'Deskjet'), ('Inkjet', 'Inkjet'), ('Laser', 'Laser'), ('Monokrom', 'Monokrom')], default='Inkjet', max_length=100),
        ),
        migrations.AlterField(
            model_name='printer',
            name='tipe_printer',
            field=models.CharField(max_length=100),
        ),
    ]
