# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-18 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190215_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('laptop_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipe_laptop', models.CharField(max_length=100)),
                ('serial_laptop', models.CharField(max_length=100)),
                ('ukuran_layar', models.CharField(choices=[('14 Inch', '14 Inch'), ('15 Inch', '15 Inch'), ('16 Inch', '16 Inch'), ('17 Inch', '17 Inch'), ('18 Inch', '18 Inch'), ('19 Inch', '19 Inch')], default='14 Inch', max_length=100)),
                ('kondisi_laptop', models.CharField(choices=[('OK', 'OK'), ('RUSAK', 'RUSAK')], default='OK', max_length=100)),
                ('serial_baterai', models.CharField(max_length=100)),
                ('serial_adaptor', models.CharField(max_length=100)),
                ('kondisi_adaptor', models.CharField(choices=[('OK', 'OK'), ('RUSAK', 'RUSAK')], default='OK', max_length=100)),
                ('status_adaptor', models.CharField(choices=[('TERPASANG', 'TERPASANG'), ('STOCK', 'STOCK')], default='OK', max_length=100)),
                ('serial_charger', models.CharField(max_length=100)),
                ('kondisi_charger', models.CharField(choices=[('OK', 'OK'), ('RUSAK', 'RUSAK')], default='OK', max_length=100)),
                ('status_baterai', models.CharField(choices=[('TERPASANG', 'TERPASANG'), ('STOCK', 'STOCK')], default='OK', max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('lokasi_penyimpanan', models.CharField(max_length=100)),
                ('catatan', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='merek',
            fields=[
                ('merek_id', models.AutoField(primary_key=True, serialize=False)),
                ('merek', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='komputer',
            old_name='nama_komputer',
            new_name='hostname',
        ),
        migrations.AddField(
            model_name='keyboard',
            name='catatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='komputer',
            name='catatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='catatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='catatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mouse',
            name='catatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pesawat_telephone',
            name='catatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='catatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='psu',
            name='catatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sistem_operasi',
            name='catatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='catatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='merek_laptop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.merek'),
        ),
    ]
