# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-18 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190218_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='kondisi_charger',
            new_name='kondisi_baterai',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='serial_charger',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status_adaptor',
            field=models.CharField(choices=[('TERPASANG', 'TERPASANG'), ('STOCK', 'STOCK'), ('TIDAK ADA', 'TIDAK ADA')], default='OK', max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status_baterai',
            field=models.CharField(choices=[('TERPASANG', 'TERPASANG'), ('STOCK', 'STOCK'), ('TIDAK ADA', 'TIDAK ADA')], default='OK', max_length=100),
        ),
    ]
