# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='lokasi_penyimpanan_gudang',
            new_name='baris',
        ),
        migrations.AddField(
            model_name='release',
            name='lantai',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='nomor_batch',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='rak',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
