# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0002_auto_20190319_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('nama_product', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='produkperpalet',
            fields=[
                ('produkperpalet_id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_produksi', models.DateField()),
                ('jumlah_dus', models.IntegerField()),
                ('jumlah_botol', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('nama_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi.product')),
            ],
        ),
    ]
