# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0005_transisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='gudangracking',
            fields=[
                ('gudangracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('blok', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=10)),
                ('tingkat', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10)),
                ('lorong', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], max_length=10)),
                ('baris', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('product_per_palet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi.productperpalet')),
            ],
        ),
        migrations.CreateModel(
            name='productkeluar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tujuan',
            fields=[
                ('tujuan_id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_tujuan', models.CharField(max_length=200)),
                ('alamat_tujuan', models.CharField(max_length=500)),
                ('nomor_segel', models.CharField(max_length=20)),
                ('referensi_qc', models.CharField(choices=[('OK', 'OK'), ('NOT OK', 'NOT OK')], max_length=10)),
                ('nomor_do', models.CharField(max_length=20)),
            ],
        ),
    ]
