# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0007_auto_20190320_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='varian',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
