# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0008_product_varian'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='gudangracking',
        #     name='product_per_palet',
        # ),
        # migrations.RemoveField(
        #     model_name='productkeluar',
        #     name='tujuan',
        # ),
        # migrations.RemoveField(
        #     model_name='productperpalet',
        #     name='nama_product',
        # ),
        # migrations.RemoveField(
        #     model_name='transisi',
        #     name='product_per_palet',
        # ),
        # migrations.DeleteModel(
        #     name='gudangracking',
        # ),
        # migrations.DeleteModel(
        #     name='product',
        # ),
        # migrations.DeleteModel(
        #     name='productkeluar',
        # ),
        # migrations.DeleteModel(
        #     name='productperpalet',
        # ),
        # migrations.DeleteModel(
        #     name='transisi',
        # ),
        # migrations.DeleteModel(
        #     name='tujuan',
        # ),
    ]
