# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0011_auto_20190320_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='release',
        ),
    ]
