# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0012_delete_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('produksi_id', models.AutoField(primary_key=True, serialize=False)),
                ('nomor_batch', models.IntegerField()),
                ('nomor_palet', models.IntegerField()),
                ('jumlah_dus', models.IntegerField()),
                ('jumlah_botol', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('rak', models.CharField(max_length=10)),
                ('lantai', models.CharField(max_length=10)),
                ('baris', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='productkeluar',
        ),
        migrations.RemoveField(
            model_name='tujuan',
            name='nomor_do',
        ),
        migrations.RemoveField(
            model_name='tujuan',
            name='nomor_segel',
        ),
        migrations.RemoveField(
            model_name='tujuan',
            name='referensi_qc',
        ),
    ]
