# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0013_auto_20190320_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='productkeluar',
            fields=[
                ('productkeluar_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_product', models.CharField(max_length=500)),
                ('nomor_segel', models.CharField(max_length=20)),
                ('referensi_qc', models.CharField(choices=[('OK', 'OK'), ('NOT OK', 'NOT OK')], max_length=10)),
                ('nomor_do', models.CharField(max_length=20)),
                ('tujuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi.tujuan')),
            ],
        ),
    ]
