# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0020_auto_20190327_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productperpalet',
            old_name='nama_product',
            new_name='kode_product',
        ),
        migrations.AddField(
            model_name='product',
            name='deskripsi',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
