# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0021_auto_20190327_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='productperpalet',
            name='nomor_palet',
            field=models.CharField(default='111111', max_length=100),
            preserve_default=False,
        ),
    ]
