# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0022_productperpalet_nomor_palet'),
    ]

    operations = [
        migrations.CreateModel(
            name='departement',
            fields=[
                ('departement_id', models.AutoField(primary_key=True, serialize=False)),
                ('departement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi.departement')),
            ],
        ),
    ]
