# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0024_instagram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instagram',
        ),
    ]
