# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0026_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='lokasipenyimpanan',
            fields=[
                ('lokasi_penyimpanan_id', models.AutoField(primary_key=True, serialize=False)),
                ('tempat', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='transisi',
            name='status_perpindahan',
            field=models.CharField(choices=[('CONVEYOR', 'CONVEYOR'), ('GUDANG TRANSISI', 'GUDANG TRANSISI'), ('GUDANG HCI', 'GUDANG HCI'), ('GUDANG RACKING', 'GUDANG RACKING')], max_length=100),
        ),
    ]
