# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0028_auto_20190404_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_product',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
