# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0029_auto_20190404_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_product',
            name='warna',
            field=models.CharField(default='HITAM', max_length=100),
            preserve_default=False,
        ),
    ]
