# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0030_status_product_warna'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='status_product',
            new_name='jenis_status',
        ),
    ]
