# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0033_auto_20190404_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='status_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_per_palet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi.productperpalet')),
                ('status_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi.jenis_status')),
            ],
        ),
    ]
