# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0041_productperpalet_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productperpalet',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='productperpalet',
            name='tanggal_produksi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
