# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0042_auto_20190408_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='transisi',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
