# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0043_transisi_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transisi',
            name='update_time',
        ),
    ]
