# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0047_auto_20190408_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkeluar',
            name='pengguna',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='produksi.pengguna'),
            preserve_default=False,
        ),
    ]
