# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0048_productkeluar_pengguna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transisi',
            name='update_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
