# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0052_auto_20190409_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productperpalet',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='gudangracking',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productkeluar',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productperpalet',
            name='tanggal_produksi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='status_product',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
