# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0056_remove_transisi_status_perpindahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transisi',
            name='status_perpindahannya',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='produksi.lokasipenyimpanan'),
            preserve_default=False,
        ),
    ]
