# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0057_transisi_status_perpindahannya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transisi',
            name='pengguna',
        ),
        migrations.RemoveField(
            model_name='transisi',
            name='product_per_palet',
        ),
        migrations.RemoveField(
            model_name='transisi',
            name='status_perpindahannya',
        ),
        migrations.DeleteModel(
            name='transisi',
        ),
    ]
