# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0058_auto_20190411_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='transisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi.pengguna')),
                ('product_per_palet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi.productperpalet')),
                ('status_perpindahannya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi.lokasipenyimpanan')),
            ],
        ),
    ]
